### ISSUE TITLE
Did you realize it?

### ISSUE THREAD

**Issue by adi-works** [mihi4/SimRig#2]
Hi,

Nice work on this. Did you realize these plans? are there any pics of the final product?

**Comment by mihi4** [comment]
Hi!

 

Jepp, most of the rig ist done now.
http://f16simulator.net

check out the Racingrig category ;)

 

new update will come tomorrow, I finally finished the baseframe and seat assembly (tease attached ;))

 

greetings

michi
 

Gesendet: Samstag, 25. April 2020 um 15:37 Uhr
Von: "Adi Sahar" <notifications@github.com>
An: "mihi4/SimRig" <SimRig@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [mihi4/SimRig] Did you realize it? (#2)


 

Hi,

Nice work on this. Did you realize these plans? are there any pics of the final product?

**Comment by adi-works** [comment]
Thanks. I'm looking forward to build one based on modular aluminum pillars.

**Comment by mihi4** [comment]
Yeah, that's a common way to do it.

The modularity and possibility to change/adapt the thing are really great!

 

Just too expensive for me - and I wanted to learn welding anyways :D

(material costs for the steel were 70,-)

 

BTW, the new article on the website is online: http://f16simulator.net/wp/en/2020/04/25/racingrig-06/


 

greetings

michi

 

Gesendet: Samstag, 25. April 2020 um 22:36 Uhr
Von: "Adi Sahar" <notifications@github.com>
An: "mihi4/SimRig" <SimRig@noreply.github.com>
Cc: "Michi Hirczy" <mi.hi@gmx.net>, "Comment" <comment@noreply.github.com>
Betreff: Re: [mihi4/SimRig] Did you realize it? (#2)


 

Thanks. I'm looking forward to build one based on modular aluminum pillars.

**Comment by adi-works** [comment]
Thanks a lot of your help. 👍
